name: RPGJS Dev Environment CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  init-env:
    name: Initialize Dev Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
   

      - name: Install RPGJS Dependencies
        run: npm ci

      - name: Verify Environment Build
        run: npm run build
